# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3228a979abaf10574774085c9e18950ca70201948eccd7d69472be4cce610af0bae0221987115bf0d48cf1478c76e2a1d972875225cbe949825adf55493ab96

test:
  secret_key_base: 8fd06392d8a5b3e1924f4eada5e6fb18886a0c4ddbedf01cd0efbfc72db37b7bb4ccc64c518317a37c6255449967436e25388fca9f5d70579753f47385dc4427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
